### PR TITLE
Instantiate proxy classes via reflection, remove Enhancer.createFactory

### LINKED ISSUE #75: Cache related issue with class definitions
Hi,

Since CGLIB 3.2.1+ (including 3.2.3) I experience the following error:

```
net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
	at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:332)
	at net.sf.cglib.proxy.Enhancer.generate(Enhancer.java:445)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:85)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:83)
	at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:108)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:282)
	at net.sf.cglib.proxy.Enhancer.nextInstance(Enhancer.java:643)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:286)
	at net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:433)
	at net.sf.cglib.proxy.Enhancer.create(Enhancer.java:304)
	at org.apache.wicket.jmx.Initializer.createProxy(Initializer.java:295)
	at org.apache.wicket.jmx.Initializer.register(Initializer.java:249)
	at org.apache.wicket.jmx.Initializer.init(Initializer.java:192)
	at org.apache.wicket.Application.initInitializers(Application.java:568)
	at org.apache.wicket.Application.initApplication(Application.java:776)
	at org.apache.wicket.protocol.http.WicketFilter.init(WicketFilter.java:431)
	at org.apache.wicket.protocol.http.WicketFilter.init(WicketFilter.java:355)
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:137)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:856)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:346)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1380)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:259)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:518)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:405)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.apache.wicket.examples.StartExamples.main(StartExamples.java:110)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:409)
	at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:323)
	... 36 more
Caused by: java.lang.LinkageError: loader (instance of  org/eclipse/jetty/webapp/WebAppClassLoader): attempted  duplicate class definition for name: "org/apache/wicket/jmx/Application"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	... 42 more
```

There is no such error with 3.2.0.
The CGLIB related code that is involved is https://github.com/apache/wicket/blob/7973959f169a1c44c1de18a6acde21c8b926d64c/wicket-jmx/src/main/java/org/apache/wicket/jmx/Initializer.java#L256-L294

Any idea what could be the reason ?

### PR DESCRIPTION
**Pull request by vlsi**
Here's alternative approach to class instantiation (this PR is alternative to #79).

Note: the same generated class might be used with different constructors later, thus there should be something like an inline cache (otherwise it will end up with some kind of search for the proper constructor).

Here I implement 1-entry inline cache (== remember just one constructor for the class, and use it).
If user uses more than one constructor per proxy, the code falls back to `ReflectionUtils.newInstance(...)`, and it will be rather slow: https://github.com/cglib/cglib/pull/82/files#diff-173a9c4b512f39086ed564b6320318e2R422

The results are as follows:

# Before

```
1.7u55, factory
Benchmark                                                    Mode  Cnt     Score    Error   Units
BeansBenchmark.newInstance                                   avgt   10   201,222 ±  3,494   ns/op
BeansBenchmark.newInstance:·gc.alloc.rate                    avgt   10  1251,090 ± 21,714  MB/sec
BeansBenchmark.newInstance:·gc.alloc.rate.norm               avgt   10   264,000 ±  0,001    B/op

1.8u60, factory
Benchmark                                                    Mode  Cnt     Score    Error   Units
BeansBenchmark.newInstance                                   avgt   10   146,819 ±  2,805   ns/op
BeansBenchmark.newInstance:·gc.alloc.rate.norm               avgt   10   264,000 ±  0,001    B/op
```

# After

NOTE: the results are for happy-case scenario (i.e. just one constructor is used)
Otherwise the code falls back to old `getDeclaredConstructor` path: https://github.com/cglib/cglib/pull/82/files#diff-173a9c4b512f39086ed564b6320318e2R422

```
1.7u55, reflection
Benchmark                                                    Mode  Cnt     Score    Error   Units
BeansBenchmark.newInstance                                   avgt   10   208,021 ±  6,498   ns/op
BeansBenchmark.newInstance:·gc.alloc.rate.norm               avgt   10   256,000 ±  0,001    B/op

1.8u60, reflection
Benchmark                                                    Mode  Cnt     Score    Error   Units
BeansBenchmark.newInstance                                   avgt   10   162,185 ±  3,051   ns/op
BeansBenchmark.newInstance:·gc.alloc.rate.norm               avgt   10   256,000 ±  0,001    B/op
```

closes #75

### CODE REVIEW

File: cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java [hunk 1]
```diff
@@ -413,10 +394,58 @@ private void validate() {
...
+        private final Method setThreadCallbacks;
+        private final Class[] primaryConstructorArgTypes;
+        private final Constructor primaryConstructor;
 
-        public EnhancerFactoryData(Class generatedClass) {
+        public EnhancerFactoryData(Class generatedClass, Class[] primaryConstructorArgTypes, boolean classOnly) {
             this.generatedClass = generatedClass;
+            try {
+                setThreadCallbacks = getCallbacksSetter(generatedClass, SET_THREAD_CALLBACKS_NAME);
+                setThreadCallbacks.setAccessible(true);
```
Comment (sameb) [inline cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java]: is this necessary?  it doesn't look like it was done before.

File: cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java [hunk 2]
```diff
@@ -413,10 +394,58 @@ private void validate() {
...
+                    throw new CodeGenerationException(e.getTargetException());
+                }
+            } finally {
+                // clear thread callbacks to allow them to be gc'd
+                setThreadCallbacks(null);
+            }
+
+        }
+
+        private void setThreadCallbacks(Callback[] callbacks) {
```
Comment (sameb) [inline cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java]: it looks like this is in addition to the pre-existing Enhancer.setThreadCallbacks method, which used setCallbacksHelper.  are either of those still necessary?  if so, can you add docs explaining the difference and when you'd use one vs the other?

File: cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java (hunk 1 above)
Comment (vlsi) [inline cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java]: Does it hurt? I just thought it would enable some flexibility of the method declaration.

File: cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java [hunk 3]
```diff
@@ -413,10 +394,58 @@ private void validate() {
...
+                }
+            } catch (NoSuchMethodException e) {
+                throw new CodeGenerationException(e);
+            }
+        }
+
+        public Object newInstance(Class[] argumentTypes, Object[] arguments, Callback[] callbacks) {
+            setThreadCallbacks(callbacks);
+            try {
+                if (!Arrays.equals(primaryConstructorArgTypes, argumentTypes)) {
```
Comment (sameb) [inline cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java]: does Arrays.equals internally have a short-circuit for a==b?  if not, given that i think the majority of use cases they'll be ==, we invert this and do:
  if (a == b || Arrays.equals(a, b)) {
    createFromCxtor
  } else {
    createGettingCxtor
  }

File: cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java [hunk 4]
```diff
@@ -413,10 +394,58 @@ private void validate() {
...
+                    return ReflectUtils.newInstance(generatedClass, argumentTypes, arguments);
+                }
+                try {
+                    return primaryConstructor.newInstance(arguments);
```
Comment (sameb) [inline cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java]: why not use ReflectUtils.newInstance(cxtor, args) ?  does setAccessible have a very large amount of overhead?

File: cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java (hunk 2 above)
Comment (vlsi) [inline cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java]: Frankly speaking, I do not like the idea of `threadCallbacks` at all. I would rather call a constructor that accepts callbacks, and uses accordingly.

Back to the topic:
1) `Enhancer.setThreadCallbacks` does not cache `java.lang.reflect.Method`
2) `EnhancerFactoryData` caches `reflect.Method`, that is what makes this invocation fast.

`EnhancerFactoryData` is private, so I do not expect users to call it or even know of its existence.

Re `Enhancer.setThreadCallbacks`, I would suggest to add a note that the method might be slow (or wire cache there somehow).

File: cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java (hunk 1 above)
Comment (sameb) [inline cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java]: i'd prefer to keep changes limited to what's actually necessary.  if we aren't changing the method declaration, let's not make changing it flexible.  if/when someone wants to change it, they can update this too.

File: cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java (hunk 4 above)
Comment (vlsi) [inline cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java]: `ReflectUtils.newInstance` overheads are:
1) overload lookup. It tries to lookup constructor at each invocation
2) it does not cache `java.lang.reflect` stuff

File: cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java (hunk 2 above)
Comment (sameb) [inline cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java]: Yes, lots of things within cglib are confusing and if designed from scratch might not turn out as they did.  Oh well, we live with what we have.

I understand why you added this code, for precisely the reasons you outline.  My question is: are the old methods still necessary, and if so, please add documentation explaining when you'd use one vs the other.  The documentation is intended for the reader of the code, to understand WTF they're seeing, not for the user of Enhancer.

File: cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java (hunk 3 above)
Comment (vlsi) [inline cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java]: It does have a short circuit. Do you think it deserves a comment?

File: cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java (hunk 4 above)
Comment (sameb) [inline cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java]: ReflectUtils has an overloead that takes the cxtor: https://github.com/cglib/cglib/blob/dc50ef6dbf6f525e7cd62e034e8c8d7771842e2f/cglib/src/main/java/net/sf/cglib/core/ReflectUtils.java#L240 .  The only additional work it does is call setAccessible.

File: cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java (hunk 3 above)
Comment (sameb) [inline cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java]: yeah might as well comment it to avoid future folks thinking about it.

File: cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java (hunk 4 above)
Comment (vlsi) [inline cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java]: Technically speaking, it tries to revert setAccessible as well. I'm not sure what implications that would have in multithreaded environment where several threads would want to alter accessibility of the same instance at exactly the same time.

Comment (sameb) [inline cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java]: in your specific scenario, no implications because it will always be == true from the initial call.  in the general case: who knows.  but not relevant here.

File: cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java (hunk 3 above)
Comment (vlsi) [inline cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java]: I've added explicit reference check to make the intention clear, and to make the code "jvm-independent"

**Comment by sameb** [comment]
lgtm with the exception of some comment clarifications.  LMK if you're able to update the comments and i'll merge after.  thanks!

File: cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java (hunk 4 above)
Comment (vlsi) [inline cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java]: I've added `if (not_yet_accessible)` checks to `net.sf.cglib.core.ReflectUtils#newInstance(java.lang.reflect.Constructor, java.lang.Object[])` and reused that method here.

File: cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java [hunk 5]
```diff
@@ -402,35 +402,38 @@ public EnhancerFactoryData(Class generatedClass, Class[] primaryConstructorArgTy
...
-                try {
-                    return primaryConstructor.newInstance(arguments);
-                } catch (InstantiationException e) {
-                    throw new CodeGenerationException(e);
-                } catch (IllegalAccessException e) {
-                    throw new CodeGenerationException(e);
-                } catch (InvocationTargetException e) {
-                    throw new CodeGenerationException(e.getTargetException());
+                // Explicit reference equality is added here just in case Arrays.equals does not have one
+                if (primaryConstructorArgTypes == argumentTypes &&
```
Comment (sameb) [inline cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java]: change && to ||.

Comment (vlsi) [inline cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java]: indeed. Done that, thanks.

**Comment by vlsi** [comment]
@sameb , I think this is one is ready.

**Comment by sameb** [comment]
Could you add a test that this fixes #75 ?
